# See https://cloud.google.com/appengine/docs/php/config/appref
runtime: php55
api_version: 1

handlers:
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true
  
- url: /css
  static_dir: css

# Serve php scripts.
- url: /$
  script: index.php
  
  
- url: /(.+\.php)$
  script: \1

env_variables:
  MYSQL_DSN: 'enter mysql dsn'
  MYSQL_USER: 'enter user name'
  MYSQL_PASSWORD: 'enter user password'
